// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 The MCDF Project
#pragma once

// Umbrella header for the MCDF library.
#include "mcdf/version.hpp"
#include "mcdf/error.hpp"
#include "mcdf/container/container.hpp"
#include "mcdf/container/directory_container.hpp"
#include "mcdf/container/tar.hpp"
#include "mcdf/container/tar_container.hpp"
#include "mcdf/container/open.hpp"
#include "mcdf/model/metadata.hpp"
#include "mcdf/model/schema.hpp"
#include "mcdf/model/manifest.hpp"
#include "mcdf/model/document.hpp"
#include "mcdf/model/audit.hpp"
#include "mcdf/serialize/markdown.hpp"
#include "mcdf/serialize/audit_log.hpp"
#include "mcdf/serialize/render.hpp"
#include "mcdf/serialize/parsers.hpp"
#include "mcdf/serialize/canonical_json.hpp"
#include "mcdf/crypto/hash.hpp"
#include "mcdf/crypto/encoding.hpp"
#include "mcdf/crypto/keys.hpp"
#include "mcdf/crypto/jws.hpp"
#include "mcdf/crypto/aead.hpp"
#include "mcdf/crypto/enc_keys.hpp"
#include "mcdf/model/encryption_policy.hpp"
#include "mcdf/serialize/policy_yaml.hpp"
#include "mcdf/core/manifest_ops.hpp"
#include "mcdf/core/validate.hpp"
#include "mcdf/core/sign_ops.hpp"
#include "mcdf/core/pack_ops.hpp"
#include "mcdf/core/encrypt_ops.hpp"
#include "mcdf/core/audit_ops.hpp"
#include "mcdf/core/render.hpp"
