// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Sukesh Ashok Kumar and The MCDF Project
//
// Offline support, generated at build time.
//
// Hand-rolled rather than `vite-plugin-pwa` (house rule: ask before
// adding a dependency, and prefer in-house where the surface is small). What
// this app actually needs is narrow: precache a fixed, self-contained bundle;
// serve it cache-first; never touch the network for anything else — the spec
// forbids fetching external resources, so there is nothing to negotiate. That
// is ~60 lines of service worker, against a plugin whose Workbox runtime is
// larger than the code it would manage here.
//
// It also keeps two invariants that are easy to lose to a generic plugin:
//   * the precache list is exactly what the build emitted, so a missing asset
//     is a build error rather than a blank page in a tunnel, and
//   * a new version never activates under a live editor — see `sw.js` below.

import { createHash } from 'node:crypto';

import type { Plugin } from 'vite';

/** Emitted assets that are pointless to precache. */
function isPrecacheable(fileName: string): boolean {
  return !fileName.endsWith('.map') && fileName !== 'sw.js';
}

function serviceWorker(cacheName: string, base: string, urls: string[]): string {
  const list = JSON.stringify(urls, null, 2);
  return `// SPDX-License-Identifier: Apache-2.0
// Generated by vite-pwa.ts — do not edit. Cache: ${cacheName}
const CACHE = ${JSON.stringify(cacheName)};
const BASE = ${JSON.stringify(base)};
const PRECACHE = ${list};

self.addEventListener('install', (event) => {
  // No skipWaiting: a new version must not replace the running one under an
  // open editor. It takes over once every tab is closed, and the app shows a
  // "reload for the new version" notice in the meantime.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  // The page asks for this explicitly, from the reload notice.
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

// \`ignoreVary\` is load-bearing, not defensive tidying. Static hosts send
// \`Vary: Origin\` (vite preview) and \`Vary: Accept-Encoding\` (GitHub Pages).
// Precache entries are fetched by this worker, which sends neither header,
// while a \`<script type="module">\` is a CORS-mode request and always sends
// \`Origin\` — so strict Vary matching misses every JS chunk, and the app loads
// its shell offline and then dies fetching its own code. Exactly one
// representation of each URL is ever cached here, so Vary has nothing to
// distinguish.
const MATCH = { ignoreSearch: true, ignoreVary: true };

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE)) return;

  // A navigation to any in-scope path is the SPA shell. Serving it from the
  // cache is what makes the app open with no network at all.
  if (request.mode === 'navigate') {
    event.respondWith(caches.match(BASE, MATCH).then((hit) => hit ?? fetch(request)));
    return;
  }

  event.respondWith(
    caches.match(request, MATCH).then((hit) => {
      if (hit !== undefined) return hit;
      return fetch(request).then((response) => {
        // Only cache what the build could have emitted; an opaque or error
        // response would poison the shell.
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          void caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`;
}

function webmanifest(base: string): string {
  return JSON.stringify(
    {
      name: 'MCDF Web',
      short_name: 'MCDF',
      description:
        'Author, verify, sign and encrypt MCDF documents entirely in your browser. Nothing is uploaded.',
      id: base,
      start_url: base,
      scope: base,
      display: 'standalone',
      orientation: 'any',
      background_color: '#ffffff',
      theme_color: '#0b5cad',
      categories: ['productivity', 'utilities'],
      icons: [
        { src: `${base}icon.svg`, sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
        { src: `${base}icon.svg`, sizes: 'any', type: 'image/svg+xml', purpose: 'maskable' },
      ],
    },
    null,
    2,
  );
}

export function mcdfPwa(): Plugin {
  let base = '/';
  let isBuild = false;

  return {
    name: 'mcdf-pwa',

    configResolved(config) {
      base = config.base;
      isBuild = config.command === 'build';
    },

    transformIndexHtml() {
      return [
        { tag: 'link', attrs: { rel: 'manifest', href: `${base}manifest.webmanifest` }, injectTo: 'head' },
        { tag: 'link', attrs: { rel: 'icon', type: 'image/svg+xml', href: `${base}icon.svg` }, injectTo: 'head' },
        { tag: 'link', attrs: { rel: 'apple-touch-icon', href: `${base}icon.svg` }, injectTo: 'head' },
        { tag: 'meta', attrs: { name: 'theme-color', content: '#0b5cad' }, injectTo: 'head' },
      ];
    },

    generateBundle(_options, bundle) {
      this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: webmanifest(base) });

      // Precache exactly what this build produced, plus the entry points that
      // are not bundle members. `base` itself covers the shell so a navigation
      // to `/MCDF/` resolves offline.
      const urls = [
        base,
        `${base}index.html`,
        `${base}manifest.webmanifest`,
        `${base}icon.svg`,
        ...Object.keys(bundle).filter(isPrecacheable).map((f) => `${base}${f}`),
      ];

      // Name the cache after its own contents: a deploy that changes nothing
      // reuses the cache, and one that changes anything gets a fresh one.
      const hash = createHash('sha256').update(urls.join('\n')).digest('hex').slice(0, 12);
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: serviceWorker(`mcdf-web-${hash}`, base, [...new Set(urls)].sort()),
      });
    },

    configureServer(server) {
      // In dev there is no bundle to precache, and a stale worker serving old
      // modules is a genuinely confusing bug. Serve a worker that unregisters
      // itself, so a developer who installed the app once is not stuck with it.
      if (isBuild) return;
      server.middlewares.use((req, res, next) => {
        if (req.url !== `${base}sw.js` && req.url !== '/sw.js') return next();
        res.setHeader('Content-Type', 'text/javascript');
        res.end(
          '// dev build: no offline cache\n' +
            "self.addEventListener('install', () => self.skipWaiting());\n" +
            "self.addEventListener('activate', (e) => e.waitUntil(self.registration.unregister()));\n",
        );
      });
    },
  };
}
