<!--
  SPDX-License-Identifier: Apache-2.0
  Copyright (c) 2026 Sukesh Ashok Kumar and The MCDF Project

  Metadata: native form controls with real <label>s. This is the free
  accessibility win over Studio's ImGui equivalent — labels, tab order, and
  screen-reader value reporting all come from the platform.
-->
<script lang="ts">
  import Panel from '../components/Panel.svelte';
  import type { DocumentStore } from '../state/document.svelte.ts';

  interface Props {
    store: DocumentStore;
  }

  let { store }: Props = $props();

  function addAuthor(): void {
    store.metadata = {
      ...store.metadata,
      authors: [...store.metadata.authors, { name: '', id: '' }],
    };
  }

  function removeAuthor(index: number): void {
    store.metadata = {
      ...store.metadata,
      authors: store.metadata.authors.filter((_, i) => i !== index),
    };
  }
</script>

<Panel title="Metadata" badge={store.hasMetadata ? undefined : 'absent'} tone="warn">
  {#if !store.hasMetadata}
    <p class="empty">This document has no <code>metadata.yaml</code>.</p>
    <button type="button" onclick={() => store.addMetadata()}>Add metadata</button>
  {:else}
    <div class="grid">
      <p class="field">
        <label for="meta-title">Title</label>
        <input id="meta-title" type="text" bind:value={store.metadata.title} />
      </p>
      <p class="field">
        <label for="meta-version">Version</label>
        <input id="meta-version" type="text" bind:value={store.metadata.version} />
      </p>
      <p class="field">
        <label for="meta-created">Created</label>
        <input
          id="meta-created"
          type="text"
          inputmode="numeric"
          placeholder="2026-07-29"
          bind:value={store.metadata.created_at}
        />
      </p>
      <p class="field">
        <label for="meta-classification">Classification</label>
        <input
          id="meta-classification"
          type="text"
          list="classification-options"
          bind:value={store.metadata.classification}
        />
        <datalist id="classification-options">
          <option value="public"></option>
          <option value="internal"></option>
          <option value="confidential"></option>
        </datalist>
      </p>
      <p class="field">
        <label for="meta-language">Language</label>
        <input id="meta-language" type="text" placeholder="en" bind:value={store.metadata.language} />
      </p>
    </div>

    <fieldset class="authors">
      <legend>Authors</legend>
      {#if store.metadata.authors.length === 0}
        <p class="empty">No authors listed.</p>
      {/if}
      {#each store.metadata.authors as author, i (i)}
        <div class="author">
          <p class="field">
            <label for="author-name-{i}">Name</label>
            <input id="author-name-{i}" type="text" bind:value={author.name} />
          </p>
          <p class="field">
            <label for="author-id-{i}">Identifier</label>
            <input
              id="author-id-{i}"
              type="text"
              placeholder="did:key:z6Mk…"
              bind:value={author.id}
            />
          </p>
          <button type="button" onclick={() => removeAuthor(i)}>
            Remove<span class="visually-hidden"> author {i + 1}{author.name ? `, ${author.name}` : ''}</span>
          </button>
        </div>
      {/each}
      <button type="button" onclick={addAuthor}>Add author</button>
    </fieldset>

    {#if store.metadata.generated_by !== undefined}
      <p class="provenance">
        Provenance: generated by <code>{store.metadata.generated_by}</code>
      </p>
    {/if}
  {/if}
</Panel>

<style>
  .empty {
    color: var(--fg-muted);
    margin: 0.25rem 0;
  }

  .grid {
    display: grid;
    gap: 0.5rem;
  }

  .field {
    display: grid;
    gap: 0.15rem;
    margin: 0;
  }

  .field label {
    font-size: 0.8rem;
    color: var(--fg-muted);
  }

  .authors {
    margin: 0.75rem 0 0;
    padding: 0.5rem 0.6rem 0.6rem;
    border: 1px solid var(--border);
    border-radius: var(--radius);
  }

  legend {
    font-size: 0.8rem;
    color: var(--fg-muted);
    padding: 0 0.25rem;
  }

  .author {
    display: grid;
    gap: 0.35rem;
    padding-bottom: 0.5rem;
    margin-bottom: 0.5rem;
    border-bottom: 1px solid var(--border);
  }

  .provenance {
    margin: 0.6rem 0 0;
    font-size: 0.8rem;
    color: var(--fg-muted);
  }
</style>
